[settings]
name = "mindflow"
version = "0.0.9"
description = "Official default browser extension for MindFlow. "
why = "Use this extension to have access to the web."
authors = ["Run Tu <run-tu@gmail.com>"]
license = "MIT"
readme = "README.md"

[setup]
instructions="docs/instructions.md"
docs = "docs/docs.md"
source = "https://github.com/MindFlow/browser.git"

[dependencies]
gradio_client = "^1.3.0" 
toml = "^0.10"
rich = "^14.0"
